name: StackAndBlast
options:
  bundleIdPrefix: com.piotrgebski
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

packages:
  GoogleMobileAds:
    url: https://github.com/googleads/swift-package-manager-google-mobile-ads
    from: "11.2.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"  # iPhone and iPad

targets:
  StackAndBlast:
    type: application
    platform: iOS
    sources:
      - path: StackAndBlast
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.piotrgebski.StackAndBlast
        PRODUCT_NAME: "Stack & Blast"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_KEY_CFBundleDisplayName: "Stack & Blast"
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown"
        INFOPLIST_KEY_UIStatusBarStyle: UIStatusBarStyleLightContent
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: true
        SWIFT_EMIT_LOC_STRINGS: true
        # Google AdMob test application ID — replace with real ID before release
        INFOPLIST_KEY_GADApplicationIdentifier: "ca-app-pub-3940256099942544~1458002511"
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        Release:
          SWIFT_COMPILATION_MODE: wholemodule
    dependencies:
      - sdk: SpriteKit.framework
      - sdk: GameKit.framework
      - sdk: StoreKit.framework
      - sdk: AVFoundation.framework
      - sdk: CoreHaptics.framework
      - package: GoogleMobileAds
        product: GoogleMobileAds
